convoy-gluster-volume:
    metadata:
        volume_pool: "${VOLUME_POOL}"
        gluster_stack: "${GLUSTER_STACK}"
        gluster_service: "${GLUSTER_SERVICE}"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
convoy-gluster-storagepool:
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
